### ISSUE TITLE
CLI pravděpodobně neakcpetuje jpylyzer_path k jpylyzer.py

### ISSUE THREAD

**Issue by westfood** [NLCR/komplexni-validator#20]
```
[vagrant@vagrant00 jpylyzer-1.17.0]$ jpylyzer/jpylyzer.py -v
1.17.0
[vagrant@vagrant00 jpylyzer-1.17.0]$ realpath jpylyzer/jpylyzer.py
/opt/jpylyzer/jpylyzer-1.17.0/jpylyzer/jpylyzer.py
[vagrant@vagrant00 jpylyzer-1.17.0]$
```

```
[vagrant@vagrant00 KomplexniValidatorCLI-v1.3-dev]$ java -jar KomplexniValidatorCLI-1.3-dev.jar --psp-dir /opt/data/ulg001-0000y2/ --config-dir validatorConfig/ --jhove-path /opt/jhove/ --jpylyzer-path /opt/jpylyzer/jpylyzer-1.17.0/
no kakadu path
Platforma: Linux; 64b
Kořenový adresář konfigurace validátoru: /opt/validator/KomplexniValidatorCLI-v1.3-dev/validatorConfig
Kontroluji dostupnost nástroje ImageMagick: nenalezen (Cannot run program "convert": error=2, Adresář nebo soubor neexistuje)
Kontroluji dostupnost nástroje JHOVE: nalezen, verze: Rel. 1.14.6
Kontroluji dostupnost nástroje Jpylyzer: nenalezen (Cannot run program "/opt/jpylyzer/jpylyzer-1.17.0/jpylyzer": error=13, Operace zamítnuta)
Kontroluji dostupnost nástroje Kakadu: nenalezen (Cannot run program "kdu_expand": error=2, Adresář nebo soubor neexistuje)
Zpracovávám PSP balík /opt/data/ulg001-0000y2
Bude použita verze standardu Periodical 1.0
Exception in thread "main" nkp.pspValidator.shared.FdmfRegistry$UnknownFdmfException: Není definována fDMF (formalizovaná DMF) pro: Periodical 1.0
        at nkp.pspValidator.shared.FdmfRegistry.getFdmfConfig(FdmfRegistry.java:90)
        at npk.pspValidator.cli.Main.runValidator(Main.java:293)
        at npk.pspValidator.cli.Main.main(Main.java:241)
        at npk.pspValidator.cli.Main.main(Main.java:30)
```

ani

```
[vagrant@vagrant00 KomplexniValidatorCLI-v1.3-dev]$ java -jar KomplexniValidatorCLI-1.3-dev.jar --psp-dir /opt/data/ulg001-0000y2/ --config-dir validatorConfig/ --jhove-path /opt/jhove/ --jpylyzer-path /opt/jpylyzer/jpylyzer-1.17.0/jpylyzer
no kakadu path
Platforma: Linux; 64b
Kořenový adresář konfigurace validátoru: /opt/validator/KomplexniValidatorCLI-v1.3-dev/validatorConfig
Kontroluji dostupnost nástroje ImageMagick: nenalezen (Cannot run program "convert": error=2, Adresář nebo soubor neexistuje)
Kontroluji dostupnost nástroje JHOVE: nalezen, verze: Rel. 1.14.6
Kontroluji dostupnost nástroje Jpylyzer: nenalezen (Cannot run program "/opt/jpylyzer/jpylyzer-1.17.0/jpylyzer/jpylyzer": error=2, Adresář nebo soubor neexistuje)
Kontroluji dostupnost nástroje Kakadu: nenalezen (Cannot run program "kdu_expand": error=2, Adresář nebo soubor neexistuje)
Zpracovávám PSP balík /opt/data/ulg001-0000y2
Bude použita verze standardu Periodical 1.0
Exception in thread "main" nkp.pspValidator.shared.FdmfRegistry$UnknownFdmfException: Není definována fDMF (formalizovaná DMF) pro: Periodical 1.0
        at nkp.pspValidator.shared.FdmfRegistry.getFdmfConfig(FdmfRegistry.java:90)
        at npk.pspValidator.cli.Main.runValidator(Main.java:293)
        at npk.pspValidator.cli.Main.main(Main.java:241)
        at npk.pspValidator.cli.Main.main(Main.java:30)
```

wiki:

Pro ostatní platformy je možné spustit Jpylyzer jako Python skript. Kromě instalace Pythonu je potřeba stáhnout a rozbalit zdrojové kódy konkrétní verze z https://github.com/openpreserve/jpylyzer/releases (Source code (zip) nebo Source code (tar.gz)). Více na http://jpylyzer.openpreservation.org/installation.html.

Nastavení pracovního adresáře

Pokud Validátor nenachází Jpylyzer, je **potřeba nastavit pracovní adresář obsahující soubor** jpylyzer.exe (Windows), jplyzer (Debian, Ubuntu, apod.), nebo **jpylyzer.py (ostatní)**. Např. C:\Program Files\jpylyzer pro Windows.

**Comment by rzeh4n** [comment]
Správně je první možnost, tedy 
`--jpylyzer-path /opt/jpylyzer/jpylyzer-1.17.0/`.  A pouští se pak `/opt/jpylyzer/jpylyzer-1.17.0/jpylyzer`.
Vypadá to, že `/opt/jpylyzer/jpylyzer-1.17.0/jpylyzer/jpylyzer` nemá nastavená správná prava. Zde se ukazuje výstup při spuštění `/opt/jpylyzer/jpylyzer-1.17.0/jpylyzer/jpylyzer.py`. 
Pro přizpůsobení přizpůsobit volání některého z nástrojů je potřeba upravit soubor [imageUtils.xml](https://github.com/NLCR/komplexni-validator/blob/master/sharedModule/src/main/resources/nkp/pspValidator/shared/validatorConfig/imageUtils.xml) v rámci použitého **validatorConfig**, konkrétně tady nahradit řádek 5:
`<command>${PATH}jpylyzer --version</command>`
za 
`<command>${PATH}jpylyzer.py -v</command>`
